Unit Tests
GigiDev7/airlines-reservation pull request #27
Opened 2022-07-05 10:41 UTC by GigiDev7

2022-07-05 10:42 UTC, GigiDev7 commented
Is it how it should be done?

2022-07-05 17:46 UTC, Lokki17 requested changes
Add more tests :)

2022-07-05 17:46 UTC, Lokki17 commented on server/unit tests/user.test.js
> +describe("user services", () => {
little bit tests... :)

2022-07-05 18:15 UTC, Lokki17 approved these changes

2022-07-08 16:18 UTC, Lokki17 approved these changes

2022-07-08 16:24 UTC, merged